### ISSUE TITLE
Unable to create; repeated message 'Select a URL to convert to rich text link'

### ISSUE THREAD

**Issue by thatrossachap** [dhamaniasad/obsidian-rich-links#2]
I'd been looking for a plug-in to serve exactly this purpose for a while but alas, I'm struggling to get this working.

I have tried URLS typed out normally and in the []() layout; I've tried it with the link clicked, with it selected, etc.; and I can't get it to work. I just get the message and nothing changes.

Hope you can help me out with this as it looks like a great extension

**Comment by dhamaniasad** [comment]
I got the Select a URL error message too, but it did create the rich link:

https://www.loom.com/share/ceb13d8bb5c34b069e1ebf2dc7a277b8

Are you using it the same way?

**Comment by thatrossachap** [comment]
Having left it a few hours, it worked - I still get the notification but it works now. 

The only issue is that I use the 'California Coast' theme and that messes up the look of it, but with the default theme, the previews are working perfectly
